default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: 'postgres://postgres:password@localhost/_development'

test:
  <<: *default
  url: 'postgres://postgres:password@localhost/_test'

production:
  <<: *default
  database: fakepay_app_production
  username: fakepay_app
  password: <%= ENV['FAKEPAY_APP_DATABASE_PASSWORD'] %>
